name: Testing CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro dev pytest
